# Generated by Django 6.0.6 on 2026-07-01 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_id", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("owner_name", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("center_lat", models.FloatField(default=6.9214)),
                ("center_lng", models.FloatField(default=122.079)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "farm_id")},
            },
        ),
        migrations.CreateModel(
            name="RubberTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tree_id", models.CharField(max_length=20)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                (
                    "disease",
                    models.CharField(
                        choices=[
                            ("Healthy", "Healthy"),
                            ("Pink Disease", "Pink Disease"),
                            ("White Root Rot", "White Root Rot"),
                            ("Stem Bleeding", "Stem Bleeding"),
                        ],
                        default="Healthy",
                        max_length=30,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("date_scanned", models.DateField()),
                ("block", models.CharField(blank=True, max_length=10)),
                ("recommended_action", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trees",
                        to="farmmap.farm",
                    ),
                ),
            ],
            options={
                "unique_together": {("farm", "tree_id")},
            },
        ),
        migrations.CreateModel(
            name="ScanHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("disease", models.CharField(max_length=30)),
                ("confidence", models.FloatField()),
                ("inspector", models.CharField(blank=True, max_length=100)),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="farmmap.rubbertree",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
