# Generated by Django 6.0.6 on 2026-07-05 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_id", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("owner_name", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("center_lat", models.FloatField(default=6.9214)),
                ("center_lng", models.FloatField(default=122.079)),
                ("boundary_radius_m", models.PositiveIntegerField(default=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "farm_id")},
            },
        ),
        migrations.CreateModel(
            name="RubberTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tree_id", models.CharField(max_length=40, unique=True)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                (
                    "disease",
                    models.CharField(
                        choices=[
                            ("Healthy", "Healthy"),
                            ("Pink Disease", "Pink Disease"),
                            ("White Root Rot", "White Root Rot"),
                            ("Stem Bleeding", "Stem Bleeding"),
                        ],
                        default="Healthy",
                        max_length=30,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("severity_score", models.FloatField(blank=True, default=0.0)),
                ("date_scanned", models.DateField()),
                ("block", models.CharField(blank=True, max_length=10)),
                ("recommended_action", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trees",
                        to="farmmap.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Fungicide Application", "Fungicide Application"),
                            ("Bark Removal", "Bark Removal"),
                            ("Root Treatment", "Root Treatment"),
                            ("Uprooting", "Uprooting"),
                            ("Quarantine", "Quarantine"),
                            ("Soil Treatment", "Soil Treatment"),
                            ("Tapping Suspended", "Tapping Suspended"),
                            ("Monitoring Only", "Monitoring Only"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=40,
                    ),
                ),
                ("date_performed", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interventions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="farmmap.rubbertree",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_performed"],
            },
        ),
        migrations.CreateModel(
            name="ScanHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("disease", models.CharField(max_length=30)),
                ("confidence", models.FloatField()),
                ("inspector", models.CharField(blank=True, max_length=100)),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="farmmap.rubbertree",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
