# Generated by Django 6.0.7 on 2026-07-15 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='rubbertree',
            name='root_condition',
            field=models.CharField(blank=True, choices=[('Healthy Roots', 'Healthy Roots'), ('Exposed Roots Detected', 'Exposed Roots Detected')], max_length=30),
        ),
        migrations.AddField(
            model_name='rubbertree',
            name='root_image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/roots/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='rubbertree',
            name='trunk_image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/trunks/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 15, 8, 37, 53, 646605, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='root_condition',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='root_image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/roots/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='trunk_image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/trunks/%Y/%m/'),
        ),
    ]
