# Generated by Django 6.0.7 on 2026-07-15 22:58

import farmmap.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmmap', '0002_alter_scanhistory_options_rubbertree_root_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Must match the CNN model's class label exactly.", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Shown in the Disease Class Reference card, e.g. causal pathogen + visible symptoms.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('color_hex', models.CharField(default='#6c757d', help_text='e.g. #dc3545', max_length=7)),
                ('marker_key', models.SlugField(help_text="URL-safe key used in templates/JS, e.g. 'pink_disease'", max_length=30)),
                ('danger_rank', models.PositiveSmallIntegerField(default=1, help_text='0=healthy. Used only for heatmap/marker intensity, not severity tiering.')),
                ('is_healthy', models.BooleanField(default=False, help_text='Exactly one disease class should be marked Healthy.')),
                ('recommendation_mild', models.TextField(blank=True)),
                ('recommendation_moderate', models.TextField(blank=True)),
                ('recommendation_severe', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Disease classes',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='rubbertree',
            name='disease',
            field=models.CharField(choices=farmmap.models.get_disease_choices, default='Healthy', max_length=50),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='disease',
            field=models.CharField(max_length=50),
        ),
    ]
