# Generated by Django 6.0.7 on 2026-07-15 22:58

from django.db import migrations

INITIAL_DISEASES = [
    dict(
        name="Healthy", display_order=0, color_hex="#28a745", marker_key="healthy",
        danger_rank=0, is_healthy=True,
        description="Normal bark appearance, no lesions or fungal growth. Routine monitoring only.",
        recommendation_mild="No action needed. Continue regular monitoring every 30 days.",
        recommendation_moderate="", recommendation_severe="",
    ),
    dict(
        name="Pink Disease", display_order=1, color_hex="#dc3545", marker_key="pink",
        danger_rank=1, is_healthy=False,
        description="Caused by Erythricium salmonicolor. Pink corticioid fungal crust on bark.",
        recommendation_mild="Early-stage Pink Disease. Apply a copper-based fungicide preventively and monitor weekly.",
        recommendation_moderate="Apply fungicide (Mancozeb 80% WP) and remove infected bark. Recheck in 2 weeks.",
        recommendation_severe="Advanced spread — remove and destroy severely affected bark/branches, apply systemic fungicide immediately, and suspend tapping on this tree.",
    ),
    dict(
        name="White Root Rot", display_order=2, color_hex="#8b5a2b", marker_key="white_root",
        danger_rank=2, is_healthy=False,
        description="Caused by Rigidoporus lignosus. White mycelial fans at root collar.",
        recommendation_mild="Early signs of White Root Rot. Improve soil drainage and apply Trichoderma biocontrol preventively.",
        recommendation_moderate="Uproot and destroy infected roots. Treat soil with Trichoderma biocontrol.",
        recommendation_severe="High risk of spread to neighboring trees — uproot and destroy the tree and connected root system, quarantine the block, treat soil, and inspect adjacent trees.",
    ),
    dict(
        name="Stem Bleeding", display_order=3, color_hex="#8b0000", marker_key="stem_bleeding",
        danger_rank=3, is_healthy=False,
        description="Caused by Phytophthora palmivora. Dark exudate on trunk.",
        recommendation_mild="Minor bark lesions. Scrape and apply Metalaxyl paste; resume tapping after 30 days.",
        recommendation_moderate="Scrape off infected bark. Apply Metalaxyl paste. Avoid tapping for 60 days.",
        recommendation_severe="Severe stem bleeding — halt tapping entirely, apply systemic fungicide, and consult an agricultural technician about possible removal.",
    ),
]


def seed_diseases(apps, schema_editor):
    DiseaseClass = apps.get_model("farmmap", "DiseaseClass")
    for entry in INITIAL_DISEASES:
        DiseaseClass.objects.get_or_create(name=entry["name"], defaults=entry)


def remove_seeded_diseases(apps, schema_editor):
    DiseaseClass = apps.get_model("farmmap", "DiseaseClass")
    DiseaseClass.objects.filter(name__in=[d["name"] for d in INITIAL_DISEASES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('farmmap', '0003_diseaseclass_alter_rubbertree_disease_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_diseases, remove_seeded_diseases),
    ]
