# Generated by Django 6.0.6 on 2026-07-17 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmmap', '0004_seed_initial_disease_classes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_lookback_days', models.PositiveIntegerField(default=7, help_text='Only scans within this many days show up as a notification.')),
                ('notify_pink_disease', models.BooleanField(default=True)),
                ('notify_white_root_rot', models.BooleanField(default=True)),
                ('notify_stem_bleeding', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
