# Generated by Django 6.0.6 on 2026-08-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmmap", "0005_usersettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scanhistory",
            options={"ordering": ["-date", "-created_at"]},
        ),
    ]
