# Generated by Django 6.0.6 on 2026-08-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmmap', '0007_seed_more_disease_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubbertree',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
