# Generated by Django 6.0.6 on 2026-08-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmmap', '0010_farm_psgc_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubbertree',
            name='block',
        ),
    ]
